language: node_js
node_js:
 - "node"

cache:
  directories:
    - 'node_modules'

before_install:
  - npm -g install npm@latest

script:
    - npm run test
    - npm run prettier

after_success:
  - chmod +x ./scripts/publish_on_netlify.sh
  - ./scripts/publish_on_netlify.sh
