language: node_js

cache:
  directories:
    - 'node_modules'

before_install:
  - npm -g install npm@latest

script:
    - npm test
    - prettier --single-quote --list-different "src/**/*.jsx"

after_success:
  - chmod +x ./scripts/publish_on_netlify.sh
  - ./scripts/publish_on_netlify.sh
