name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Check types
        run: npm run type-check
      - name: Build with Gatsby
        run: npm run build
