name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: npm run lint
