name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint code
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: setup, lint
    steps:
      - name: Check types
        run: npm run type-check

  build:
    runs-on: ubuntu-latest
    needs: setup, lint, typecheck
    steps:
      - name: Build with Gatsby
        run: npm run build
