name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  setup:
    name: Setup
    steps:
      - name: npm ci
        uses: docker://node:10-alpine
        run: npm ci
