name: Continuous Integration
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run type-check
