name: Refresh data
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh
        run: |
          curl https://alexxie.com
          curl https://alex.xie.codes
          curl https://xie.codes
          curl https://alexxie.ca
