name: Refresh data
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh
        run: |
          curl https://alexxie.com/ping
          curl https://alex.xie.codes/ping
          curl https://xie.codes/ping
          curl https://alexxie.ca/ping
